# Site settings
author: Mauno Vähä
year: 2015
title: maunovaha.com
description: > # this means to ignore newlines until "baseurl:"
  An epic journey of a man from beginner to pro in game programming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maunovaha.com" # the base hostname & protocol for your site
twitter_username: maunovaha

# Build settings
markdown: kramdown
encoding: "utf-8"
permalink: /blog/2015/01/06/an-epic-journey-of-a-man-from-beginner-to-pro-in-game-programming

# defaults:
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
#       permalink: /blog/:year/:month/:day/:title
